### ISSUE TITLE
How integarate library with cucumber-junit output file

### ISSUE THREAD

**Issue by IvanNaumenko** [pterolex/nightwatch-teamcity#2]
Hey! 

I use nightwatch-cucumber framework. And I'd like to add nightwatch-teamcity library after cucumber-junit output=>generates xml report. How to do it correctly?

**Comment by pterolex** [comment]
Hey!

I'm not sure `nightwatch-teamcity` can be directly used with `nightwatch-cucumber`. I checked its docs and it seems that Nightwatch runner is replaced with the Cucumber so it has different output format. Also, the Nightwatch runner's `--reporter` option is not supported.

**Comment by IvanNaumenko** [comment]
I can generate xml reporter by cucumber-junit lib. Well, what should I integrate nightwatch-teamcity with it?

**Comment by pterolex** [comment]
@IvanNaumenko  JUnit report is a different format and `nightwatch-teamcity` doesn't support it. You can write an additional script to preprocess your results which `nightwatch-teamcity` can accept
